
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[264] =
    {   0,
       65,   65,   67,   67,   88,   88,   99,   98,   97,   98,
       70,   98,   30,   98,   28,   98,   31,   98,   69,   98,
       43,   98,   44,   98,   25,   98,   23,   98,   52,   98,
       24,   98,   53,   98,   26,   98,   56,   98,   56,   98,
       51,   98,   50,   98,   40,   98,   42,   98,   41,   98,
       96,   98,   47,   98,   48,   98,   29,   98,   96,   98,
       96,   98,   96,   98,   96,   98,   96,   98,   96,   98,
       96,   98,   96,   98,   96,   98,   96,   98,   96,   98,
       96,   98,   96,   98,   96,   98,   45,   98,   33,   98,
       46,   98,   32,   98,   65,   98,   65,   98,   67,   98,

       68,   98,   67,   98,   71,   98,   92,   98,   94,   98,
       98,   72,   98,   95,   98,   93,   98,   98,   88,   98,
       63,   54,   27,   57,   56,   49,   34,   38,   36,   39,
       35,   96,   96,   96,   11,   96,   96,   96,   96,   96,
       96,   96,    4,   96,   10,   96,   96,   96,   96,    2,
       96,   96,   96,   96,   96,   96,   37,   65,   65, 8256,
       65,16448,   67,   67,   67,   66,   67,   71,   79,   91,
       78,   89,   80,   81,   82,   83,   84,   85,   86,   77,
       87,   72,   90,   88,   55,   57,   58,   59,    1,   96,
       96,   96,   15,   96,   96,    9,   96,   96,   96,   96,

       18,   96,    3,   96,   96,   96,   96,   96,   96,   96,
     8256,   65,   78,   77,   76,   96,    6,   96,   96,   96,
       21,   96,   96,   96,   96,    5,   96,   16,   96,   96,
       96,   78,   75,   76,   60,   14,   96,   96,   17,   96,
       96,   22,   96,   96,   96,   13,   96,   12,   96,   73,
        7,   96,   96,    8,   96,   20,   96,   96,   19,   96,
       74,   61,   62
    } ;

static const flex_int16_t yy_accept[349] =
    {   0,
        1,    1,    1,    2,    3,    4,    5,    5,    5,    5,
        5,    6,    7,    8,    9,   11,   13,   15,   17,   19,
       21,   23,   25,   27,   29,   31,   33,   35,   37,   39,
       41,   43,   45,   47,   49,   51,   53,   55,   57,   59,
       61,   63,   65,   67,   69,   71,   73,   75,   77,   79,
       81,   83,   85,   87,   89,   91,   93,   95,   97,   99,
      101,  103,  105,  107,  109,  111,  112,  114,  116,  118,
      119,  121,  121,  122,  123,  124,  125,  126,  126,  126,
      126,  127,  128,  129,  130,  131,  132,  133,  134,  135,
      137,  138,  139,  140,  141,  142,  143,  145,  147,  148,

      149,  150,  152,  153,  154,  155,  156,  157,  158,  159,
      160,  163,  164,  165,  166,  168,  169,  170,  171,  172,
      173,  174,  175,  176,  177,  178,  179,  179,  180,  181,
      182,  183,  184,  185,  185,  186,  187,  187,  188,  189,
      189,  191,  192,  193,  195,  196,  198,  199,  200,  201,
      203,  205,  206,  207,  208,  209,  210,  211,  213,  214,
      214,  215,  216,  216,  216,  216,  217,  219,  220,  221,
      223,  224,  225,  226,  228,  230,  231,  232,  233,  233,
      233,  234,  235,  235,  235,  236,  236,  238,  239,  241,
      242,  244,  245,  246,  248,  250,  250,  250,  251,  251,

      251,  253,  254,  256,  258,  258,  258,  258,  258,  259,
      259,  259,  259,  259,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  264,  264
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   29,   30,   28,
       31,   32,   33,   34,   34,   34,   34,   34,   34,   35,
       34,   34,   34,   36,   34,   34,   34,   37,   34,   34,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,   34,   52,   53,   34,   54,
       55,   56,   34,   57,   58,   59,   60,   61,   62,   63,
       34,   64,   65,   66,   67,   68,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[69] =
    {   0,
        1,    2,    3,    1,    2,    1,    1,    1,    2,    4,
        1,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        5,    1,    1,    1,    1,    1,    1,    5,    5,    5,
        6,    6,    6,    6,    6,    6,    6,    1,    2,    1,
        1,    7,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    1,    8,    1
    } ;

static const flex_int16_t yy_base[371] =
    {   0,
        0,    0,   66,   67,   68,   69,   71,   76,   81,   86,
       89,   93,  551,  552,  552,  552,  552,  552,  552,  552,
      485,  552,  552,  552,  552,  534,  532,  530,   98,   82,
      524,  552,   82,  520,   96,    0,  552,  552,  552,  490,
      486,  487,   70,   39,  486,   78,  485,   76,  482,  491,
       80,  483,  486,  552,  552,  552,  510,    0,  108,  494,
      552,  109,    0,  552,  552,  158,    0,  552,  552,  133,
      136,  504,  552,  516,  552,  133,  139,  153,    0,  468,
      552,  552,  552,  552,  552,  552,    0,  484,  482,    0,
      470,  481,  473,  468,  470,  464,    0,    0,  477,  468,

      461,    0,   85,  472,  458,  458,  465,  552,    0,  118,
        0,  475,  125,  145,  150,    0,  552,  552,  163,  552,
      552,  552,  552,  552,  552,  552,  449,  552,  205,  552,
        0,  552,  144,  480,  552,  173,  189,  209,  160,  475,
        0,  468,  463,    0,  451,    0,  463,  452,  463,    0,
        0,  458,  444,  449,  455,  450,  447,    0,  218,  489,
        0,    0,  467,  241,  457,  444,  444,  447,  434,    0,
      439,  448,  433,    0,    0,  436,  441,  552,  421,  419,
      552,  552,  452,  222,  226,  474,    0,  435,    0,  431,
        0,  422,  426,    0,    0,  414,  411,  552,  441,  411,

        0,  420,    0,    0,  442,  406,  405,  439,  416,  439,
      401,  456,  436,    0,  428,  397,  451,  425,  419,  393,
      443,  416,  428,  389,  445,  425,  420,  385,  424,  417,
      418,  438,  416,  413,  426,  411,  407,  431,  405,  373,
      374,  371,  372,  407,  424,  413,  400,  420,  417,  399,
      413,  361,  394,  416,  414,  388,  396,  355,  354,  410,
      552,  407,  399,  351,  405,  350,  349,  384,  380,  378,
      380,  378,  371,  374,  364,  369,  375,  336,  369,  388,
      369,  388,  365,  387,  360,  368,  327,  371,  380,  325,
      324,  351,  323,  340,  354,  355,  354,  343,  345,  343,

      338,  366,  349,  361,  342,  332,  340,  341,  334,  299,
      327,  331,  292,  323,  342,  321,  340,  307,  322,  295,
      297,  256,  294,  295,  192,  246,  217,  552,  176,  196,
      174,  175,  198,  190,  164,  173,  134,  169,  163,  158,
      155,  151,   97,  100,  100,  552,  552,  262,  270,  278,
      286,  294,  298,  305,  313,  321,  329,   82,  337,  341,
      344,   72,   69,  345,  349,  353,  357,  361,  365,  369
    } ;

static const flex_int16_t yy_def[371] =
    {   0,
      347,    1,  348,  348,  349,  349,  350,  350,  351,  351,
      352,  352,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  353,  347,  347,  347,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  347,  347,  347,  347,  354,  354,  355,
      347,  355,  356,  347,  347,  347,  357,  347,  347,   66,
      347,  347,  347,  347,  347,  347,  347,  347,  358,  347,
      347,  347,  347,  347,  347,  347,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  347,  354,  354,
      359,  355,  355,  355,  355,  356,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  360,  347,
      357,  347,  347,  347,  347,  347,  347,  347,  358,  347,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  359,  347,  361,
      362,  363,  347,  347,  347,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  347,  347,  364,
      347,  347,  347,  347,  347,  347,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  347,  365,  347,  347,  347,

      353,  353,  353,  353,  347,  366,  347,  347,  353,  347,
      367,  347,  347,  353,  347,  368,  347,  347,  347,  369,
      347,  347,  347,  370,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,    0,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347
    } ;

static const flex_int16_t yy_nxt[621] =
    {   0,
       14,   14,   15,   14,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   30,
       30,   31,   32,   33,   34,   35,   14,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   37,   14,   38,
       39,   36,   40,   41,   36,   42,   43,   44,   45,   36,
       46,   36,   47,   48,   49,   36,   50,   36,   51,   52,
       36,   53,   36,   36,   54,   55,   56,   57,   14,   14,
       61,   61,   14,   14,  182,   64,  181,   14,   14,   65,
       64,   93,   14,   14,   65,   68,  139,   14,   14,   69,
       68,   71,   71,   94,   69,   71,   71,   76,   95,   77,

       77,   77,   77,   59,   59,   82,   83,   62,   62,   66,
      346,   78,  345,   76,   66,   77,   77,   77,   77,   70,
       85,   86,   91,   92,   70,   97,  100,   78,   78,  104,
      101,   98,  110,  114,   79,   80,  105,  132,  133,  133,
      152,  347,  110,  153,   78,  111,  133,  133,  115,  114,
      136,  136,  136,  136,   76,  111,   77,   77,   77,   77,
       79,  117,   78,  344,  115,  137,  118,  137,   78,  114,
      138,  138,  138,  138,  114,  119,  119,  119,  119,   78,
      159,  159,  159,  159,  115,   78,  343,  342,  341,  115,
      136,  136,  136,  136,  164,  340,  120,  339,  338,  337,

      121,  122,   78,  336,  335,  123,  138,  138,  138,  138,
      334,  124,  333,  332,  125,  164,  126,  127,  128,   78,
      129,  130,  161,  161,  161,  161,  138,  138,  138,  138,
      331,  330,  161,  161,  161,  178,  178,  178,  178,  185,
      185,  185,  185,  185,  185,  185,  185,  161,  161,  161,
      161,  161,  161,  184,  329,  184,  328,  327,  185,  185,
      185,  185,   58,   58,   58,   58,   58,   58,   58,   58,
       60,   60,   60,   60,   60,   60,   60,   60,   63,   63,
       63,   63,   63,   63,   63,   63,   67,   67,   67,   67,
       67,   67,   67,   67,   14,   14,   14,   14,   14,   14,

       14,   14,   87,   87,   87,  109,  109,  326,  109,  109,
      109,  109,  109,  112,  112,  325,  112,  112,  112,  112,
      112,  116,  324,  323,  116,  116,  116,  116,  116,  131,
      322,  321,  131,  131,  131,  131,  131,  158,  158,  320,
      158,  158,  158,  158,  158,  162,  162,  180,  180,  197,
      319,  318,  197,  206,  317,  316,  206,  211,  315,  314,
      211,  216,  313,  312,  216,  220,  311,  310,  220,  224,
      309,  308,  224,  228,  307,  306,  228,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,

      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  198,  231,  230,  229,  198,  227,  226,  225,  198,
      223,  222,  221,  198,  219,  218,  217,  198,  215,  214,
      213,  212,  198,  210,  209,  208,  207,  198,  205,  204,
      203,  202,  201,  200,  199,  198,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  183,  179,  177,

      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  163,  160,  113,  157,  156,  155,  154,  151,
      150,  149,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  135,  134,  113,  108,  107,  106,  103,  102,   99,
       96,   90,   89,   88,   84,   81,   75,   74,   73,   72,
      347,   13,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347
    } ;

static const flex_int16_t yy_chk[621] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    6,    7,    7,  363,    7,  362,    8,    8,    7,
        8,   44,    9,    9,    8,    9,  358,   10,   10,    9,
       10,   11,   11,   44,   10,   12,   12,   30,   44,   30,

       30,   30,   30,    3,    4,   33,   33,    5,    6,    7,
      345,   30,  344,   29,    8,   29,   29,   29,   29,    9,
       35,   35,   43,   43,   10,   46,   48,   29,   30,   51,
       48,   46,   59,   62,   29,   29,   51,   70,   71,   71,
      103,   70,  110,  103,   29,   59,  133,  133,   62,  113,
       76,   76,   76,   76,   77,  110,   77,   77,   77,   77,
       29,   66,   76,  343,  113,   78,   66,   78,   77,  114,
       78,   78,   78,   78,  115,   66,   66,   66,   66,   76,
      119,  119,  119,  119,  114,   77,  342,  341,  340,  115,
      136,  136,  136,  136,  139,  339,   66,  338,  337,  336,

       66,   66,  136,  335,  334,   66,  137,  137,  137,  137,
      333,   66,  332,  331,   66,  139,   66,   66,   66,  136,
       66,   66,  129,  129,  129,  129,  138,  138,  138,  138,
      330,  329,  129,  129,  129,  159,  159,  159,  159,  184,
      184,  184,  184,  185,  185,  185,  185,  129,  129,  129,
      129,  129,  129,  164,  327,  164,  326,  325,  164,  164,
      164,  164,  348,  348,  348,  348,  348,  348,  348,  348,
      349,  349,  349,  349,  349,  349,  349,  349,  350,  350,
      350,  350,  350,  350,  350,  350,  351,  351,  351,  351,
      351,  351,  351,  351,  352,  352,  352,  352,  352,  352,

      352,  352,  353,  353,  353,  354,  354,  324,  354,  354,
      354,  354,  354,  355,  355,  323,  355,  355,  355,  355,
      355,  356,  322,  321,  356,  356,  356,  356,  356,  357,
      320,  319,  357,  357,  357,  357,  357,  359,  359,  318,
      359,  359,  359,  359,  359,  360,  360,  361,  361,  364,
      317,  316,  364,  365,  315,  314,  365,  366,  313,  312,
      366,  367,  311,  310,  367,  368,  309,  308,  368,  369,
      307,  306,  369,  370,  305,  304,  370,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,

      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
      219,  218,  217,  216,  215,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  202,  200,  199,  197,  196,  193,
      192,  190,  188,  186,  183,  180,  179,  177,  176,  173,
      172,  171,  169,  168,  167,  166,  165,  163,  160,  157,

      156,  155,  154,  153,  152,  149,  148,  147,  145,  143,
      142,  140,  134,  127,  112,  107,  106,  105,  104,  101,
      100,   99,   96,   95,   94,   93,   92,   91,   89,   88,
       80,   74,   72,   60,   57,   53,   52,   50,   49,   47,
       45,   42,   41,   40,   34,   31,   28,   27,   26,   21,
       13,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 5 "lexer.l"
    #include <stdio.h>

    void remove_char_from_str(const char * str, char * dest, char deleted_char);
#line 748 "lex.yy.c"

#line 750 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define ML_COMMENT 2
#define STRING_SINGLE_QUOTES 3
#define STRING_DOUBLE_QUOTES 4
#define DELETE_WHITESPACE 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 24 "lexer.l"



#line 28 "lexer.l"
    enum TypeString {
        DOUBLE_QUOTES,
        SINGLE_QUOTES,
        MULTISTRING,
        UNDEFINED
    };
    
    int int_number;
    float float_number;
    char tmp1[100];
    char tmp2[100];
    char comment[1000];
    char string[1000];
    enum TypeString typeString;

    int commentLevel;



    // ++++++++++++++++++++++++++ Ключевые слова ++++++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


#line 1006 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 348 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 347 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
goto find_rule; /* Shut up GCC warning -Wall */
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 51 "lexer.l"
{ printf("Found AND keyword.\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "lexer.l"
{ printf("Found OR keyword.\n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "lexer.l"
{ printf("Found NOT keyword.\n"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 "lexer.l"
{ printf("Found IF keyword.\n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "lexer.l"
{ printf("Found THEN keyword.\n"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "lexer.l"
{ printf("Found ELSE keyword.\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "lexer.l"
{ printf("Found ELSEIF keyword.\n"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "lexer.l"
{ printf("Found REPEAT keyword.\n"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "lexer.l"
{ printf("Found FOR keyword.\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "lexer.l"
{ printf("Found IN keyword.\n"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "lexer.l"
{ printf("Found DO keyword.\n"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "lexer.l"
{ printf("Found WHILE keyword.\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "lexer.l"
{ printf("Found UNTIL keyword.\n"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "lexer.l"
{ printf("Found BREAK keyword.\n"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "lexer.l"
{ printf("Found END keyword.\n"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 69 "lexer.l"
{ printf("Found TRUE keyword.\n"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 70 "lexer.l"
{ printf("Found FALSE keyword.\n"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 71 "lexer.l"
{ printf("Found NIL keyword.\n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 73 "lexer.l"
{ printf("Found FUNCTION keyword.\n"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 74 "lexer.l"
{ printf("Found RETURN keyword.\n"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 76 "lexer.l"
{ printf("Found GOTO keyword.\n"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "lexer.l"
{ printf("Found LOCAL keyword.\n"); }
	YY_BREAK

    // +++++++++++++++++++++++++ Служебные символы ++++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case 23:
YY_RULE_SETUP
#line 85 "lexer.l"
{ printf("Found ADD operator.\n"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "lexer.l"
{ printf("Found SUB operator.\n"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "lexer.l"
{ printf("Found MUL operator.\n"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "lexer.l"
{ printf("Found DIV operator.\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "lexer.l"
{ printf("Found FLOOR_DIV operator.\n"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "lexer.l"
{ printf("Found MOD operator.\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "lexer.l"
{ printf("Found POW operator.\n"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 93 "lexer.l"
{ printf("Found LEN operator.\n"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 95 "lexer.l"
{ printf("Found BITWISE_AND operator.\n"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "lexer.l"
{ printf("Found BITWISE_XOR or BITWISE_NOT operator.\n"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 97 "lexer.l"
{ printf("Found BITWISE_OR operator.\n"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 98 "lexer.l"
{ printf("Found BITWISE_LEFT_SHIFT operator.\n"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 99 "lexer.l"
{ printf("Found BITWISE_RIGHT_SHIFT operator.\n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 101 "lexer.l"
{ printf("Found EQL operator.\n"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "lexer.l"
{ printf("Found NOT_EQL operator.\n"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "lexer.l"
{ printf("Found LE operator.\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 104 "lexer.l"
{ printf("Found GE operator.\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 105 "lexer.l"
{ printf("Found LESS operator.\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 106 "lexer.l"
{ printf("Found GREATER operator.\n"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 108 "lexer.l"
{ printf("Found ASSIGN operator.\n"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "lexer.l"
{ printf("Found OPEN_PARENTHESIS.\n"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 111 "lexer.l"
{ printf("Found CLOSE_PARENTHESIS.\n"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 112 "lexer.l"
{ printf("Found OPEN_CURLY_BRACKET.\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 113 "lexer.l"
{ printf("Found CLOSE_CURLY_BRACKET.\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "lexer.l"
{ printf("Found OPEN_SQUARE_BRACKET.\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 115 "lexer.l"
{ printf("Found CLOSE_SQUARE_BRACKET.\n"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 117 "lexer.l"
{ printf("Found GOTO_TAG_MARK.\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 118 "lexer.l"
{ printf("Found SEMICOLON_FIELDSEP.\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 119 "lexer.l"
{ printf("Found COLON operator.\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 120 "lexer.l"
{ printf("Found COMMA_FIELDSEP operator.\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 121 "lexer.l"
{ printf("Found DOT operator.\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 122 "lexer.l"
{ printf("Found CONCAT operator.\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 123 "lexer.l"
{ printf("Found VARARG.\n"); }
	YY_BREAK

    // +++++++++++++++++++++++++ Служебные символы ++++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


    // +++++++++++++++++++++++++ Служебные символы ++++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    // TODO

case 56:
YY_RULE_SETUP
#line 136 "lexer.l"
{
    printf("Found INT_DECIMAL_NUMBER %d\n", atoi(yytext));
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 140 "lexer.l"
{
    printf("Found FLOAT_DECIMAL_NUMBER %f\n", atof(yytext));
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 144 "lexer.l"
{
    printf("Found FLOAT_DECIMAL_NUMBER %f\n", atof(yytext));
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 148 "lexer.l"
{
    sscanf(yytext, "%x", &int_number);
    printf("Found INT_HEXADECIMAL_NUMBER %d\n", int_number);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 153 "lexer.l"
{
    sscanf(yytext, "%a", &float_number);
    printf("Found FLOAT_HEXADECIMAL_NUMBER %f\n", float_number);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 161 "lexer.l"
{
    printf("Found FLOAT_DECIMAL_NUMBER %f\n", atof(yytext));
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 165 "lexer.l"
{
    sscanf(yytext, "%a", &float_number);
    printf("Found FLOAT_HEXADECIMAL_NUMBER %f\n", float_number);
}
	YY_BREAK

    // +++++++++++++++++++++++++ Комментарии ++++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case 63:
YY_RULE_SETUP
#line 175 "lexer.l"
{
BEGIN(COMMENT);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 179 "lexer.l"
{
comment[0] = 0;
commentLevel = strlen(yytext) - 2;
BEGIN(ML_COMMENT);
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 185 "lexer.l"
{
printf("Нашел одиночный %s\n", yytext);
BEGIN(INITIAL);
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 190 "lexer.l"
{

int level = 0;
for(int i = strlen(yytext) - 2; i >= 0; --i) {

    if(yytext[i] == '=') {
    level += 1;
    }
    if(yytext[i] == ']') break;
}

if(commentLevel == level) {
strcat(comment, yytext);
comment[strlen(comment) - 2 - commentLevel] = 0;
printf("Нашел многострочный %s\n", comment);
commentLevel = 0;
BEGIN(INITIAL);
}
else {
strcat(comment, yytext);
}
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 213 "lexer.l"
{
strcat(comment, yytext);
}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 217 "lexer.l"
{
strcat(comment, yytext);
}
	YY_BREAK

    // +++++++++++++++++++++++++ Строки ++++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case 69:
YY_RULE_SETUP
#line 227 "lexer.l"
{
    string[0] = 0;
    typeString = SINGLE_QUOTES;
    BEGIN(STRING_SINGLE_QUOTES);
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 233 "lexer.l"
{
    string[0] = 0;
    typeString = DOUBLE_QUOTES;
    BEGIN(STRING_DOUBLE_QUOTES);
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 240 "lexer.l"
{
    //TODO Здесь поидее можно удалить \a\b\f\n\r\t\v и это \" (тогда можно удалить нижние правила)
    strcat(string, yytext); 
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 245 "lexer.l"
{
    //TODO Здесь поидее можно удалить \a\b\f\n\r\t\v и это \' (тогда можно удалить нижние правила)
    strcat(string, yytext); 
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 250 "lexer.l"
{
    //TODO Проверить
    remove_char_from_str(yytext,tmp1,'{');
    remove_char_from_str(tmp1,tmp2,'}');
    strcat(string, tmp2);
    
    // sscanf(yytext+2, "%x", &int_number);
    // tmp1[0] = int_number;
    // tmp1[1] = 0;
    // strcat(string, tmp1);
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 262 "lexer.l"
{
    //TODO Проверить
    printf("ERROR: Invalid hex escape \n");
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 267 "lexer.l"
{
    sscanf(yytext+2, "%x", &int_number);
    tmp1[0] = int_number;
    tmp1[1] = 0;
    strcat(string, tmp1);
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 274 "lexer.l"
{
    printf("ERROR: Invalid hex escape \n");
    //TODO мб надо бегин инишал сделать
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 279 "lexer.l"
{
    printf("ERROR: Invalid hex escape \n");
    //TODO мб надо бегин инишал сделать
    //TODO мб еще нужная проверка на то что там не хекс числа
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 285 "lexer.l"
{
    sscanf(yytext+1, "%d", &int_number);
    tmp1[0] = int_number;
    tmp1[1] = 0;
    strcat(string, tmp1);
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 292 "lexer.l"
{
    //TODO Надо наверн вместо пробела написать любые символы кроме букв, которые являются эскейп последовательностями и чисел
    printf("ERROR: Invalid hex escape \n");
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 297 "lexer.l"
{
    strcat(string, "\a");
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 301 "lexer.l"
{
    strcat(string, "\b");
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 305 "lexer.l"
{
    strcat(string, "\f");
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 309 "lexer.l"
{
    strcat(string, "\n");
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 313 "lexer.l"
{
    strcat(string, "\r");
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 317 "lexer.l"
{
    strcat(string, "\t");
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 321 "lexer.l"
{
    strcat(string, "\v");
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 325 "lexer.l"
{
    BEGIN(DELETE_WHITESPACE);
}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 329 "lexer.l"
{
    if(typeString == DOUBLE_QUOTES)
    {
        BEGIN(STRING_DOUBLE_QUOTES);
    }
    else if(typeString == SINGLE_QUOTES)
    {
        BEGIN(STRING_SINGLE_QUOTES);
    }
    //TODO Добавить для многострочного текста
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 341 "lexer.l"
{
    strcat(string, "\\");
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 345 "lexer.l"
{
    strcat(string, "\"");
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 349 "lexer.l"
{
    strcat(string, "'");
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 353 "lexer.l"
{
    strcat(string, "\"");
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 357 "lexer.l"
{
    strcat(string, "'");
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 361 "lexer.l"
{
    printf("Found STRING_SINGLE_QUOTES: %s\n", string);
    typeString = UNDEFINED;
    BEGIN(INITIAL);
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 367 "lexer.l"
{
    printf("Found STRING_DOUBLE_QUOTES: %s\n", string);
    typeString = UNDEFINED;
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(STRING_DOUBLE_QUOTES):
#line 373 "lexer.l"
{ 
    printf("ERROR: expected \" \n"); 
    BEGIN(INITIAL);
    }
	YY_BREAK
case YY_STATE_EOF(STRING_SINGLE_QUOTES):
#line 378 "lexer.l"
{ 
    printf("ERROR: expected ' \n");
    BEGIN(INITIAL);
    }
	YY_BREAK

    // +++++++++++++++++++++++++ _____ ++++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case 96:
YY_RULE_SETUP
#line 389 "lexer.l"
{
    printf("Found VARIABLE or FUNCTION_NAME %s\n", yytext);
}
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 393 "lexer.l"
{ 
    //printf("Found NEW_LINE\n");
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 397 "lexer.l"
ECHO;
	YY_BREAK
#line 1765 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(ML_COMMENT):
			case YY_STATE_EOF(DELETE_WHITESPACE):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 348 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 348 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 347);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 397 "lexer.l"


void remove_char_from_str(const char * str, char * dest, char deleted_char) {
	int j = 0;

    for(int i = 0; str[i] != 0; i++) {
        if(str[i] != deleted_char) {
            dest[j++] = str[i];
        }
    }

    dest[j] = 0;
}

int main(int argc, char **argv ){
	yyin = fopen(argv[1], "r" );

    yylex();
    return 0;
}
