
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 102
#define YY_END_OF_BUFFER 103
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[375] =
    {   0,
       68,   68,   70,   70,   73,   73,   92,   92,  103,  100,
      102,  101,  102,   75,  100,  102,   30,  100,  102,   28,
      100,  102,   31,  100,  102,   74,  100,  102,   43,  100,
      102,   44,  100,  102,   25,  100,  102,   23,  100,  102,
       52,  100,  102,   24,  100,  102,   53,  100,  102,   26,
      100,  102,   56,   57,  100,  102,   56,   57,  100,  102,
       51,  100,  102,   50,  100,  102,   40,  100,  102,   42,
      100,  102,   41,  100,  102,   99,  100,  102,   47,  100,
      102,   48,  100,  102,   29,  100,  102,   99,  100,  102,
       99,  100,  102,   99,  100,  102,   99,  100,  102,   99,

      100,  102,   99,  100,  102,   99,  100,  102,   99,  100,
      102,   99,  100,  102,   99,  100,  102,   99,  100,  102,
       99,  100,  102,   99,  100,  102,   99,  100,  102,   45,
      100,  102,   33,  100,  102,   46,  100,  102,   32,  100,
      102,   68,  102,  102,   68,  102,   70,  102,   70,  102,
       70,  102,   76,  102,   94,  102,   97,  102,  102,   77,
      102,   98,  102,   73,  102,   73,  102,   73,  102,   92,
      102,   66,   54,   59,   27,   57,   56,   57,   58,   49,
       34,   38,   36,   39,   35,   99,   71,   99,   99,   11,
       99,   99,   99,   99,   99,   99,   99,    4,   99,   10,

       99,   99,   99,   99,    2,   99,   99,   99,   99,   99,
       99,   37,   68,   68, 8259,   68,16451,   70,   70,   70,
     8261,   70,16453,   76,   83,   95,   96,   81,   81,   81,
       81,   93,   84,   85,   86,   87,   88,   89,   90,   80,
       91,   77,   73,   73,   73, 8264,   73,16456,   92,   55,
       60,   57,   59,   58,   57,   61,   62,   71,    1,   99,
       99,   99,   15,   99,   99,    9,   99,   99,   99,   99,
       18,   99,    3,   99,   99,   99,   99,   99,   99,   99,
     8259,   68, 8261,   70, 8261,   70, 8261,   70,16453,   81,
       81,   81,   81,   81,   79,   80, 8264,   73, 8264,   73,

     8264,   73,16456,   60,   59,   58,   60,   64,   62,   63,
       99,    6,   99,   99,   99,   21,   99,   99,   99,   99,
        5,   99,   16,   99,   99,   99, 8261,   70,   82,   79,
       78, 8264,   73,   58,   60,   57,   59,   65,   62,   64,
       63,   62,   14,   99,   99,   17,   99,   99,   22,   99,
       99,   99,   13,   99,   12,   99,   65,   64,   63,   65,
        7,   99,   99,    8,   99,   20,   99,   63,   65,   62,
       64,   99,   19,   99
    } ;

static const flex_int16_t yy_accept[235] =
    {   0,
        1,    1,    1,    2,    3,    4,    5,    5,    5,    5,
        5,    6,    7,    8,    9,   10,   12,   14,   17,   20,
       23,   26,   29,   32,   35,   38,   41,   44,   47,   50,
       53,   57,   61,   64,   67,   70,   73,   76,   79,   82,
       85,   88,   91,   94,   97,  100,  103,  106,  109,  112,
      115,  118,  121,  124,  127,  130,  133,  136,  139,  142,
      144,  145,  147,  149,  151,  153,  155,  157,  159,  160,
      162,  164,  166,  168,  170,  172,  173,  174,  175,  176,
      177,  179,  180,  180,  181,  182,  183,  184,  185,  186,
      187,  187,  188,  189,  190,  192,  193,  194,  195,  196,

      197,  198,  200,  202,  203,  204,  205,  207,  208,  209,
      210,  211,  212,  213,  214,  215,  218,  219,  220,  221,
      224,  225,  226,  227,  228,  229,  230,  231,  232,  233,
      234,  235,  236,  237,  238,  239,  240,  241,  242,  243,
      244,  245,  246,  249,  250,  251,  252,  254,  255,  256,
      256,  258,  259,  261,  262,  263,  265,  266,  268,  269,
      270,  271,  273,  275,  276,  277,  278,  279,  280,  281,
      283,  285,  287,  290,  291,  292,  293,  294,  295,  296,
      297,  299,  301,  304,  305,  306,  308,  309,  310,  311,
      312,  314,  315,  316,  318,  319,  320,  321,  323,  325,

      326,  327,  329,  330,  331,  332,  334,  336,  338,  339,
      341,  342,  343,  345,  346,  348,  349,  351,  352,  353,
      355,  357,  358,  359,  361,  363,  364,  366,  368,  370,
      372,  373,  375,  375
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   20,   21,   22,   22,   22,   22,   23,   24,   25,
       26,   27,    1,    1,   28,   28,   28,   28,   29,   28,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   31,
       30,   30,   30,   30,   30,   30,   30,   32,   30,   30,
       33,   34,   35,   36,   30,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   30,   46,   47,   30,   48,
       49,   50,   30,   51,   52,   53,   54,   55,   56,   57,
       30,   58,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    6,    6,
        6,    6,    1,    1,    1,    1,    1,    6,    6,    7,
        8,    7,    1,    9,    1,    1,    6,    6,    6,    6,
        6,    6,    7,    7,    7,    7,    7,    7,    7,    8,
        7,    7,    7,    7,    7,    7,    7,    7,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[256] =
    {   0,
        0,    0,   60,   61,   62,   63,   65,   66,   67,   72,
       69,   74,   76,   78,  625,  626,  626,  626,  626,  626,
      626,  626,  626,  626,  626,  626,  626,  610,   67,  607,
       95,  113,  599,  626,   65,  595,   69,    0,   85,  626,
      626,  572,  568,  569,   55,   71,  568,   81,  567,   77,
      564,  573,   93,  565,  568,  626,  626,  626,  585,    0,
      626,  112,  575,  626,   57,    0,  626,  626,  151,    0,
      626,  574,  626,  113,  138,  626,  592,  145,  626,  162,
      195,  208,  588,  626,  626,  626,  626,  626,  626,    0,
      117,  598,  560,  549,    0,  532,  543,  526,  513,  505,

      493,    0,    0,  506,  483,  475,    0,   96,  478,  456,
      380,  387,  626,    0,  125,    0,  395,  121,  152,  166,
        0,  626,  626,  626,  626,  220,  226,  232,  626,  626,
      626,  626,  626,  626,  626,  626,  238,  626,    0,  363,
      170,  172,  197,  158,  626,  251,  264,  270,  277,    0,
      285,  626,    0,  360,  354,    0,  323,    0,  335,  315,
      324,    0,    0,  273,  255,  260,  266,  229,  217,    0,
      227,  275,  276,  300,  306,  312,  319,  325,    0,    0,
      226,  277,  278,  331,  337,  348,  126,  144,  359,  189,
      189,  192,  178,    0,  174,  181,  160,    0,    0,  150,

      154,  280,  626,  626,  626,  337,  365,  371,  382,  169,
      388,  394,    0,  148,    0,  132,    0,  100,   73,    0,
        0,  400,  406,  417,    0,   70,    0,    0,  423,  429,
       59,    0,  626,  451,  460,  469,  478,  487,  496,  500,
      508,  517,  526,  534,  543,  551,  556,  562,  571,  580,
      588,   99,  597,   61,  600
    } ;

static const flex_int16_t yy_def[256] =
    {   0,
      233,    1,  234,  234,  235,  235,  236,  236,  237,  237,
      238,  238,  239,  239,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  240,  233,  233,
      233,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  233,  233,  233,  233,  241,
      233,  241,  242,  233,  242,  243,  233,  233,  244,  245,
      233,  246,  233,  246,  233,  233,  233,  233,  233,  233,
      233,  233,  247,  233,  233,  233,  233,  233,  233,  240,
      233,  233,  240,  240,  240,  240,  240,  240,  240,  240,

      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  233,  241,  241,  248,  242,  242,  242,  249,
      243,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  250,  233,  245,  246,
      246,  246,  251,  233,  233,  233,  233,  233,  233,  252,
      247,  233,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  248,
      249,  249,  249,  233,  233,  233,  233,  233,  253,  254,
      251,  251,  251,  233,  233,  233,  252,  255,  233,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,

      240,  249,  233,  233,  233,  251,  233,  233,  233,  255,
      233,  233,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  233,  233,  233,  240,  240,  240,  240,  233,  233,
      240,  240,    0,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233
    } ;

static const flex_int16_t yy_nxt[689] =
    {   0,
       16,   17,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   32,   32,
       32,   32,   33,   34,   35,   36,   37,   38,   38,   38,
       38,   38,   39,   16,   40,   41,   42,   43,   38,   44,
       45,   46,   47,   38,   48,   38,   49,   50,   51,   38,
       52,   38,   53,   54,   38,   55,   38,   38,   56,   57,
       58,   59,   61,   61,   64,   64,  205,   67,   67,   67,
       71,   73,   68,   68,   67,   71,   73,   75,   75,   75,
       75,   77,  119,   78,   78,   78,   78,   78,   78,   85,
       86,  120,   62,   62,   88,   89,   65,   65,   69,   69,

       69,   96,   97,   74,  187,   69,  232,   98,   74,   80,
       91,   81,   81,   81,   81,   81,   81,   92,  231,   99,
      228,  105,  102,   82,  100,  106,   83,   80,  103,   81,
       81,   81,   81,   81,   81,   82,  109,  115,  142,  144,
      144,   82,   91,  110,  116,  164,  119,  143,  165,   92,
      115,   83,  227,   82,  123,  120,  209,  116,  124,  144,
      144,   78,   78,   78,   78,   78,   78,  125,  126,  127,
      128,  128,  128,  146,  189,  209,  226,  119,  147,  147,
      147,  147,  147,  147,  129,  146,  120,  130,  131,  225,
       82,  172,  132,  189,  221,  142,  220,  142,  133,  224,

      173,  134,   82,  135,  143,  136,  143,  137,  138,   80,
      219,   81,   81,   81,   81,   81,   81,  218,  224,  148,
      217,  148,  182,   82,  149,  149,  149,  149,  149,  149,
      216,  183,  215,  214,  213,   82,  174,  174,  174,  174,
      174,  174,  175,  175,  175,  175,  176,  177,  178,  178,
      178,  178,  178,  178,  180,  180,  180,  180,  180,  180,
      206,  202,  184,  201,  184,  180,  180,  185,  185,  185,
      185,  185,  185,  200,  180,  180,  180,  180,  180,  180,
      147,  147,  147,  147,  147,  147,  149,  149,  149,  149,
      149,  149,  186,  149,  149,  149,  149,  149,  149,  188,

      172,  172,  182,  182,  186,  172,  199,  198,  197,  173,
      173,  183,  183,  196,  173,  189,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  203,  189,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  207,
      195,  207,  182,  194,  208,  208,  208,  208,  208,  208,
      211,  183,  211,  193,  192,  212,  212,  212,  212,  212,
      212,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  222,  191,  222,  190,  141,  223,  223,

      223,  223,  223,  223,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  223,  223,  223,  223,
      223,  223,  223,  223,  223,  223,  223,  223,  229,  118,
      229,  169,  168,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   90,   90,   90,  114,  167,
      114,  114,  114,  114,  114,  114,  114,  117,  166,  117,
      117,  117,  117,  117,  117,  117,  121,  163,  121,  162,
      121,  121,  121,  121,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  139,  161,  160,  139,  139,  139,  139,
      139,  140,  159,  140,  140,  140,  140,  140,  140,  140,
      151,  151,  170,  158,  170,  170,  170,  170,  170,  170,
      170,  171,  157,  171,  171,  171,  171,  171,  171,  171,
      179,  179,  156,  155,  179,  179,  179,  179,  181,  154,
      181,  181,  181,  181,  181,  181,  181,  204,  204,  153,

      152,  204,  150,  204,  204,  210,  145,  210,  141,  118,
      113,  112,  111,  108,  107,  104,  101,   95,   94,   93,
       87,   84,   79,   76,  233,   15,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233
    } ;

static const flex_int16_t yy_chk[689] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,  254,    7,    8,    9,
        9,   11,    7,    8,   10,   10,   12,   13,   13,   14,
       14,   29,   65,   29,   29,   29,   29,   29,   29,   35,
       35,   65,    3,    4,   37,   37,    5,    6,    7,    8,

        9,   45,   45,   11,  252,   10,  231,   46,   12,   31,
       39,   31,   31,   31,   31,   31,   31,   39,  226,   46,
      219,   50,   48,   31,   46,   50,   31,   32,   48,   32,
       32,   32,   32,   32,   32,   31,   53,   62,   74,   75,
       75,   32,   91,   53,   62,  108,  118,   74,  108,   91,
      115,   31,  218,   32,   69,  118,  187,  115,   69,  144,
      144,   78,   78,   78,   78,   78,   78,   69,   69,   69,
       69,   69,   69,   78,  188,  187,  216,  119,   80,   80,
       80,   80,   80,   80,   69,   78,  119,   69,   69,  214,
       80,  120,   69,  188,  201,  141,  200,  142,   69,  210,

      120,   69,   80,   69,  141,   69,  142,   69,   69,   81,
      197,   81,   81,   81,   81,   81,   81,  196,  210,   82,
      195,   82,  143,   81,   82,   82,   82,   82,   82,   82,
      193,  143,  192,  191,  190,   81,  126,  126,  126,  126,
      126,  126,  127,  127,  127,  127,  127,  127,  128,  128,
      128,  128,  128,  128,  137,  137,  137,  137,  137,  137,
      181,  171,  146,  169,  146,  137,  137,  146,  146,  146,
      146,  146,  146,  168,  137,  137,  137,  137,  137,  137,
      147,  147,  147,  147,  147,  147,  148,  148,  148,  148,
      148,  148,  147,  149,  149,  149,  149,  149,  149,  151,

      172,  173,  182,  183,  147,  202,  167,  166,  165,  172,
      173,  182,  183,  164,  202,  151,  174,  174,  174,  174,
      174,  174,  175,  175,  175,  175,  175,  175,  176,  176,
      176,  176,  176,  176,  151,  177,  177,  177,  177,  177,
      177,  178,  178,  178,  178,  178,  178,  184,  184,  184,
      184,  184,  184,  185,  185,  185,  185,  185,  185,  186,
      161,  186,  206,  160,  186,  186,  186,  186,  186,  186,
      189,  206,  189,  159,  157,  189,  189,  189,  189,  189,
      189,  207,  207,  207,  207,  207,  207,  208,  208,  208,
      208,  208,  208,  209,  155,  209,  154,  140,  209,  209,

      209,  209,  209,  209,  211,  211,  211,  211,  211,  211,
      212,  212,  212,  212,  212,  212,  222,  222,  222,  222,
      222,  222,  223,  223,  223,  223,  223,  223,  224,  117,
      224,  112,  111,  224,  224,  224,  224,  224,  224,  229,
      229,  229,  229,  229,  229,  230,  230,  230,  230,  230,
      230,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  237,  237,
      237,  237,  237,  237,  237,  237,  237,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  239,  239,  239,  239,

      239,  239,  239,  239,  239,  240,  240,  240,  241,  110,
      241,  241,  241,  241,  241,  241,  241,  242,  109,  242,
      242,  242,  242,  242,  242,  242,  243,  106,  243,  105,
      243,  243,  243,  243,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  245,  104,  101,  245,  245,  245,  245,
      245,  246,  100,  246,  246,  246,  246,  246,  246,  246,
      247,  247,  248,   99,  248,  248,  248,  248,  248,  248,
      248,  249,   98,  249,  249,  249,  249,  249,  249,  249,
      250,  250,   97,   96,  250,  250,  250,  250,  251,   94,
      251,  251,  251,  251,  251,  251,  251,  253,  253,   93,

       92,  253,   83,  253,  253,  255,   77,  255,   72,   63,
       59,   55,   54,   52,   51,   49,   47,   44,   43,   42,
       36,   33,   30,   28,   15,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
#line 5 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
    #include <stdio.h>

    int calc_long_bracket_level(const char * str);
#line 737 "lex.yy.c"

#line 739 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define ML_COMMENT 2
#define SQ_STRING 3
#define DQ_STRING 4
#define ML_STRING 5
#define REMOVING_WHITESPACES 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 27 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"



#line 31 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
    enum string_type {
        SQ,
        DQ,
        UNDEFINED
    };

    int int_number;
    float float_number;

    char tmp1[100];
    char tmp2[100];

    char comment[1000];

    char string[1000];
    enum string_type string_type;

    int long_bracket_level;



    // ++++++++++++++++++++++++++ Ключевые слова ++++++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


#line 998 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 234 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_current_state != 233 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 56 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found AND keyword.\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found OR keyword.\n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 58 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found NOT keyword.\n"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found IF keyword.\n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found THEN keyword.\n"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found ELSE keyword.\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found ELSEIF keyword.\n"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found REPEAT keyword.\n"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 66 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found FOR keyword.\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 67 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found IN keyword.\n"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 68 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found DO keyword.\n"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 69 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found WHILE keyword.\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 70 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found UNTIL keyword.\n"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 71 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found BREAK keyword.\n"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 72 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found END keyword.\n"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 74 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found TRUE keyword.\n"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 75 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found FALSE keyword.\n"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 76 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found NIL keyword.\n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 78 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found FUNCTION keyword.\n"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 79 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found RETURN keyword.\n"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found GOTO keyword.\n"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 83 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found LOCAL keyword.\n"); }
	YY_BREAK

    // +++++++++++++++++++++++++ Служебные символы ++++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case 23:
YY_RULE_SETUP
#line 90 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found ADD operator.\n"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 91 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found SUB operator.\n"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 92 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found MUL operator.\n"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 93 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found DIV operator.\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 94 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found FLOOR_DIV operator.\n"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 95 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found MOD operator.\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 96 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found POW operator.\n"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found LEN operator.\n"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 100 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found BITWISE_AND operator.\n"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 101 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found BITWISE_XOR or BITWISE_NOT operator.\n"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 102 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found BITWISE_OR operator.\n"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 103 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found BITWISE_LEFT_SHIFT operator.\n"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 104 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found BITWISE_RIGHT_SHIFT operator.\n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 106 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found EQL operator.\n"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 107 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found NOT_EQL operator.\n"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 108 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found LE operator.\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 109 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found GE operator.\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 110 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found LESS operator.\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 111 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found GREATER operator.\n"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 113 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found ASSIGN operator.\n"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 115 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found OPEN_PARENTHESIS.\n"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 116 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found CLOSE_PARENTHESIS.\n"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 117 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found OPEN_CURLY_BRACKET.\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 118 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found CLOSE_CURLY_BRACKET.\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 119 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found OPEN_SQUARE_BRACKET.\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 120 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found CLOSE_SQUARE_BRACKET.\n"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 122 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found GOTO_TAG_MARK.\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 123 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found SEMICOLON_FIELDSEP.\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 124 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found COLON operator.\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 125 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found COMMA_FIELDSEP.\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 126 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found DOT operator.\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 127 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found CONCAT operator.\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 128 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ printf("Found VARARG.\n"); }
	YY_BREAK

    // +++++++++++++++++++++++++ Числовые константы +++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case 56:
YY_RULE_SETUP
#line 135 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Found INT_DECIMAL_NUMBER <%d>.\n", atoi(yytext));
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 139 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Found FLOAT_DECIMAL_NUMBER <%f>.\n", atof(yytext));
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 143 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Error: malformed number <%s>.\n", yytext);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 147 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Found FLOAT_DECIMAL_NUMBER <%f>.\n", atof(yytext));
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 151 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Error: malformed number <%s>.\n", yytext);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 155 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    sscanf(yytext, "%x", &int_number);
    printf("Found INT_HEXADECIMAL_NUMBER <%d>.\n", int_number);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 160 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    sscanf(yytext, "%a", &float_number);
    printf("Found FLOAT_HEXADECIMAL_NUMBER <%f>.\n", float_number);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 165 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Error: malformed number <%s>.\n", yytext);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 169 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    sscanf(yytext, "%a", &float_number);
    printf("Found FLOAT_HEXADECIMAL_NUMBER <%f>.\n", float_number);
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 174 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Error: malformed number <%s>.\n", yytext);
}
	YY_BREAK

    // ++++++++++++++++++++++++++++ Комментарии +++++++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case 66:
YY_RULE_SETUP
#line 183 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    BEGIN(COMMENT);
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 187 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    comment[0] = 0;
    long_bracket_level = strlen(yytext) - 2;
    BEGIN(ML_COMMENT);
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 193 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Found COMMENT: <%s>.\n", yytext);
    BEGIN(INITIAL);
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 198 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    int level = calc_long_bracket_level(yytext);
    if(long_bracket_level == level) {
        strcat(comment, yytext);
        comment[strlen(comment) - 2 - long_bracket_level] = 0;

        printf("Found ML_COMMENT: \n<<<<<<<<\n%s\n>>>>>>>>\n", comment);

        long_bracket_level = 0;
        BEGIN(INITIAL);
    }
    else {
        strcat(comment, yytext);
    }
}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 214 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(comment, yytext);
}
	YY_BREAK

    // ++++++++++++++++++++++++ Строковые константы +++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 223 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    string[0] = 0;

    if(yytext[strlen(yytext) - 1] == '\n')
        long_bracket_level = strlen(yytext) - 3;
    else {
        long_bracket_level = strlen(yytext) - 2;
    }

    BEGIN(ML_STRING);
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 235 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    int level = calc_long_bracket_level(yytext);
    if(long_bracket_level == level) {
        strcat(string, yytext);
        string[strlen(string) - 2 - long_bracket_level] = 0;

        printf("Found ML_STRING: \n<<<<<<<<\n%s\n>>>>>>>>\n", string);

        long_bracket_level = 0;
        BEGIN(INITIAL);
    }
    else {
        strcat(string, yytext);
    }
}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 251 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, yytext);
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 255 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    string[0] = 0;
    string_type = SQ;
    BEGIN(SQ_STRING);
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 261 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    string[0] = 0;
    string_type = DQ;
    BEGIN(DQ_STRING);
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 267 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, yytext);
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 271 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, yytext);
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 275 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    sscanf(yytext + 2, "%x", &int_number);
    tmp1[0] = int_number;
    tmp1[1] = 0;
    strcat(string, tmp1);
}
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 282 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    // TODO: BEGIN(INITIAL)?
    printf("Error: invalid hex escape <%s>.\n", yytext);
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 287 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    // TODO: BEGIN(INITIAL)?
    printf("Error: invalid hex escape <%s>.\n", yytext);
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 292 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    sscanf(yytext + 1, "%d", &int_number);
    tmp1[0] = int_number;
    tmp1[1] = 0;
    strcat(string, tmp1);
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 299 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    // TODO: BEGIN(INITIAL)?
    printf("Error: invalid hex escape <%s>.\n", yytext);
}
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 304 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    // TODO: BEGIN(INITIAL)?
    printf("Error: invalid hex escape <%s>.\n", yytext);
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 309 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, "\a");
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 313 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, "\b");
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 317 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, "\f");
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 321 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, "\n");
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 325 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, "\r");
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 329 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, "\t");
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 333 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, "\v");
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 337 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    BEGIN(REMOVING_WHITESPACES);
}
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 341 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    if(string_type == SQ) {
        BEGIN(SQ_STRING);
    }
    else if(string_type == DQ) {
        BEGIN(DQ_STRING);
    }
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 350 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, "\\");
}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 354 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Error: unfinished string.\n");
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 358 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, "\"");
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 362 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    strcat(string, "'");
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 366 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Found SQ_STRING: <<%s>>\n", string);
    string_type = UNDEFINED;
    BEGIN(INITIAL);
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 372 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Found DQ_STRING: <<%s>>\n", string);
    string_type = UNDEFINED;
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(SQ_STRING):
#line 378 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Error: expected '.\n");
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(DQ_STRING):
#line 383 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Error: expected \".\n");
    BEGIN(INITIAL);
}
	YY_BREAK

    // ++++++++++++++++++++++ Пользовательские имена ++++++++++++++++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case 99:
YY_RULE_SETUP
#line 393 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Found VARIABLE or FUNCTION_NAME <%s>.\n", yytext);
}
	YY_BREAK

    // +++++++++++ Пробельные символы и символы, вызывающие ошибку ++++++++++++++++
    // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

case 100:
YY_RULE_SETUP
#line 402 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{
    printf("Error: unexpected symbol <%s>.\n", yytext);
}
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 406 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
{ }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 408 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"
ECHO;
	YY_BREAK
#line 1785 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(COMMENT):
			case YY_STATE_EOF(ML_COMMENT):
			case YY_STATE_EOF(ML_STRING):
			case YY_STATE_EOF(REMOVING_WHITESPACES):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 234 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 234 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 233);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 408 "C:\\Users\\ready\\Desktop\\FLEX\\lexer.l"


int calc_long_bracket_level(const char * str) {
    int level = 0;
    for(int i = strlen(str) - 2; i >= 0; --i) {
        if(str[i] == '=') {
            level += 1;
        }
        if(str[i] == ']') {
            break;
        }
    }
    return level;
}

int main(int argc, char ** argv){
    yyin = fopen(argv[1], "r");

    yylex();
    return 0;
}

